substitutions:
  _IMAGE_URI: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_IMAGE_URI}
      - .

images:
  - "${_IMAGE_URI}"
