from __future__ import annotations

import json
import os
from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, field_validator

from api.cloudrun_writeback import record_cloudrun_input_event

_REPO_ROOT = str(Path(__file__).resolve().parent.parent.parent)

router = APIRouter(tags=["analytics"])

def _load_lease_system_gap_analysis(limit: int | None = None) -> dict:
    """Read-only system gap analysis summary generated by scripts/lease_system_gap_analyzer.py."""
    path = Path(_REPO_ROOT) / "reports" / "lease_system_gap_analysis.json"
    if not path.exists():
        return {"available": False, "items": [], "source": str(path)}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"available": False, "items": [], "source": str(path)}
    gaps = payload.get("gaps") or []
    if not isinstance(gaps, list):
        gaps = []
    priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    items = [item for item in gaps if isinstance(item, dict)]
    items.sort(key=lambda item: (priority_order.get(str(item.get("priority") or "").lower(), 9), str(item.get("id") or "")))
    if limit is not None:
        items = items[:limit]
    counts: dict[str, int] = {}
    for item in gaps:
        if isinstance(item, dict):
            priority = str(item.get("priority") or "unknown").lower()
            counts[priority] = counts.get(priority, 0) + 1
    return {
        "available": True,
        "generated_at": str(payload.get("generated_at") or ""),
        "mode": str(payload.get("mode") or "read-only diagnostics"),
        "source": str(path),
        "counts": counts,
        "items": items,
    }



@router.get("/api/lease-system-gaps")
def get_lease_system_gaps():
    return _load_lease_system_gap_analysis()

@router.get("/api/department/stats")
def get_department_stats():
    try:
        from data_cases import load_department_stats_cache, refresh_department_stats_cache
        payload = load_department_stats_cache()
        if payload is None:
            payload = refresh_department_stats_cache()
        if payload is None:
            raise HTTPException(status_code=503, detail="department stats cache unavailable")
        return payload
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/api/visual/data")
def get_visual_data():
    from visual_insights import _build_dataframe
    import math
    try:
        df = _build_dataframe()
        if df.empty:
            return {"cases": []}
        
        # Replace NaNs and Infinities for JSON serialization
        df = df.replace([math.inf, -math.inf], None)
        df = df.where(df.notnull(), None)
        
        return {"cases": df.to_dict(orient="records")}
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/api/similar/data")
def get_similar_cases_data():
    from case_network import build_network_data
    try:
        data = build_network_data(None)
        return data
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


class SimilarInlineRequest(BaseModel):
    nenshu: float = 0
    op_profit: float = 0
    equity_ratio: float = 0
    bank_credit: float = 0
    lease_credit: float = 0
    industry_sub: str = ""
    industry_major: str = ""
    max_count: int = 3


@router.post("/api/similar/inline")
def get_similar_cases_inline(req: SimilarInlineRequest):
    """軍師パネル等にインライン表示するための類似案件抽出。"""
    from data_cases import find_similar_past_cases
    try:
        current = {
            "nenshu": req.nenshu,
            "op_profit": req.op_profit,
            "equity_ratio": req.equity_ratio,
            "bank_credit": req.bank_credit,
            "lease_credit": req.lease_credit,
            "industry_sub": req.industry_sub or req.industry_major,
        }
        results = find_similar_past_cases(current, max_count=max(1, min(int(req.max_count or 3), 5)))
        # フロントで参照する最小フィールドに整形
        compact = []
        for r in results:
            compact.append({
                "id": r.get("id"),
                "name": r.get("name") or "匿名企業",
                "industry": r.get("industry") or "",
                "score": r.get("score") or 0,
                "status": r.get("status") or "未登録",
                "similarity": r.get("similarity") or 0,
                "equity": r.get("equity") or 0,
                "revenue": r.get("revenue") or 0,
                "conditions": (r.get("data") or {}).get("loan_conditions") or [],
            })
        return {"similar_cases": compact}
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

class ReportRequest(BaseModel):
    result_data: Dict[str, Any]
    inputs: Dict[str, Any]

_REPORT_QUALITY_LOG = Path(_REPO_ROOT) / "data" / "report_quality_log.jsonl"
_report_quality_log_lock = __import__("threading").Lock()


@router.post("/api/report/generate")
def generate_report(req: ReportRequest):
    try:
        import uuid as _uuid
        from report_generator import generate_full_report_from_res
        report_id = str(_uuid.uuid4())
        dummy_session = {
            "rep_company": req.inputs.get("company_name", "（企業名未設定）"),
            "last_submitted_inputs": req.inputs,
            "humor_style": "standard"
        }
        res_data = req.result_data

        report_text = generate_full_report_from_res(res_data, dummy_session)
        return {"report_markdown": report_text, "report_id": report_id}
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


class ReportFeedbackRequest(BaseModel):
    report_id: str
    rating: Literal["good", "bad"]
    surface: str = "report_viewer"
    comment: str = ""


@router.post("/api/report-feedback")
def post_report_feedback(req: ReportFeedbackRequest) -> dict:
    import datetime as _dt, json as _json
    entry = _json.dumps({
        "ts": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "report_id": req.report_id,
        "rating": req.rating,
        "surface": req.surface,
        "comment": req.comment,
    }, ensure_ascii=False) + "\n"
    with _report_quality_log_lock:
        with open(_REPORT_QUALITY_LOG, "a", encoding="utf-8") as f:
            f.write(entry)
    return {"status": "ok"}



# =============================================================================
# 高度分析 API (Phase 15.2: TimesFM / 3期財務分析)
# =============================================================================

from pydantic import field_validator

# ── 3期財務分析 (financial) 関連 ────────────────────────────────────────────────

SEASONAL_INDICES = {
    "建設業":       [0.6, 0.7, 1.8, 0.8, 0.9, 0.9, 0.8, 0.9, 1.0, 0.9, 1.0, 1.7],
    "小売業":       [0.9, 0.8, 1.0, 0.9, 0.9, 0.9, 1.0, 1.0, 0.9, 1.0, 1.1, 1.6],
    "製造業":       [0.9, 0.9, 1.1, 1.0, 1.0, 1.0, 1.0, 0.9, 1.1, 1.0, 1.0, 1.1],
    "卸売業":       [0.9, 0.9, 1.2, 1.0, 1.0, 1.0, 1.0, 0.9, 1.0, 1.0, 1.0, 1.1],
    "医療・福祉":   [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
    "飲食・宿泊業": [0.8, 0.8, 1.0, 1.0, 1.1, 1.1, 1.3, 1.2, 1.0, 1.0, 0.9, 0.8],
    "サービス業":   [0.9, 0.9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.1, 1.1],
    "不動産業":     [0.8, 0.9, 1.4, 1.1, 1.0, 0.9, 0.9, 0.9, 1.0, 0.9, 0.9, 1.3],
    "情報通信業":   [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
    "運輸・物流":   [0.9, 0.9, 1.1, 1.0, 1.0, 0.9, 0.9, 1.0, 1.0, 1.0, 1.1, 1.2],
}
_DEFAULT_SEASONAL = [1.0] * 12

class ForecastRequest(BaseModel):
    sales:      list[float]
    profit:     list[float]
    net_assets: list[float]
    industry:   str = "サービス業"

    @field_validator("sales", "profit", "net_assets")
    @classmethod
    def must_be_three_values(cls, v: list[float]) -> list[float]:
        if len(v) != 3: raise ValueError("3 elements required")
        return v

class ForecastResponse(BaseModel):
    months_history:      list[str]
    sales_history:       list[float]
    profit_history:      list[float]
    net_assets_history:  list[float]
    months_forecast:     list[str]
    sales_forecast:      list[float]
    profit_forecast:     list[float]
    net_assets_forecast: list[float]
    timesfm_available:   bool

def _annual_to_monthly(annual_values: list[float], industry: str) -> list[float]:
    idx = SEASONAL_INDICES.get(industry, _DEFAULT_SEASONAL)
    monthly = []
    for annual in annual_values:
        monthly_mean = annual / 12.0
        for season in idx:
            monthly.append(monthly_mean * season)
    return monthly

def _run_forecast(monthly_history: list[float], horizon: int = 12) -> list[float]:
    import math
    import numpy as np
    from timesfm_engine import _timesfm_point_forecast, TIMESFM_AVAILABLE
    if TIMESFM_AVAILABLE and len(monthly_history) >= 6:
        result = _timesfm_point_forecast(monthly_history, horizon)
        if len(result) == horizon:
            return [float(v) for v in result]
    # Fallback to GBM
    if not monthly_history or monthly_history[-1] <= 0: return [0.0] * horizon
    arr = np.clip(np.array(monthly_history, dtype=float), 1e-6, None)
    log_r = np.diff(np.log(arr))
    mu = float(np.mean(log_r)) if len(log_r) > 0 else 0.01
    S0 = monthly_history[-1]
    dt = 1.0 / 12
    return [S0 * math.exp(mu * (t + 1) * dt) for t in range(horizon)]

def _make_month_labels(start_year: int, start_month: int, count: int) -> list[str]:
    labels = []
    y, m = start_year, start_month
    for _ in range(count):
        labels.append(f"{y:04d}-{m:02d}")
        m += 1
        if m > 12: m = 1; y += 1
    return labels

class FutureSimulationRequest(BaseModel):
    """将来財務シミュレーションの入力。金額はすべて千円（CLAUDE.md の数値単位を参照）。"""

    sales: float = Field(..., description="現在の売上高（千円）")
    op_profit: float = Field(0.0, description="現在の営業利益（千円）")
    drift: float = Field(0.01, ge=-0.5, le=0.5, description="年間期待成長率")
    volatility: float = Field(0.15, gt=0.0, le=1.0, description="年間ボラティリティ")
    years: int = Field(5, ge=1, le=10)
    # 上限を切らないと1リクエストでワーカーを長時間占有できてしまうため固定で頭打ちにする
    n_simulations: int = Field(5000, ge=100, le=20000)
    use_timesfm: bool = False
    sales_history: Optional[List[float]] = None
    case_id: str = ""


class FutureSimulationActualRequest(BaseModel):
    """予測後に判明した財務実績。金額は千円、判定には自動反映しない。"""

    case_id: str = Field(..., min_length=1, max_length=200)
    observed_year: int = Field(..., ge=1, le=10, description="予測基準年から何年後の実績か")
    sales: Optional[float] = None
    op_profit: Optional[float] = None
    observed_at: date = Field(..., description="実績の観測日。予測後の情報混入を防ぐため必須")
    source: str = Field("manual_financial_actual", max_length=80)

    @field_validator("observed_at")
    @classmethod
    def validate_observed_at(cls, value: date) -> date:
        if value > date.today():
            raise ValueError("実績日に未来日は指定できません")
        return value


@router.post("/api/future-simulation")
def api_future_simulation(req: FutureSimulationRequest) -> dict:
    """案件の将来売上・営業利益を確率的にシミュレーションする。

    計算は future_simulation_core.py（Streamlit 版と同じ関数）を使う。
    case_id を渡すと、審査時点の数値予測として記録する（記録のみ。
    スコアや判定には影響しない）。
    """
    from future_simulation_core import run_business_simulation, simulation_to_json

    simulation = run_business_simulation(
        current_sales=req.sales,
        current_op_profit=req.op_profit,
        drift=req.drift,
        volatility=req.volatility,
        years=req.years,
        n_simulations=req.n_simulations,
        use_timesfm=req.use_timesfm,
        sales_history=req.sales_history,
    )
    payload = simulation_to_json(simulation)
    if payload is None:
        return {"available": False, "reason": "sales_must_be_positive"}

    recorded = {"status": "skipped", "reason": "case_id_not_provided"}
    if req.case_id.strip():
        from api.prediction_snapshot import record_numeric_forecast

        recorded = record_numeric_forecast(
            case_id=req.case_id,
            forecast=payload,
            assumptions={
                "sales": req.sales,
                "op_profit": req.op_profit,
                "drift": req.drift,
                "volatility": req.volatility,
                "years": req.years,
                "use_timesfm": req.use_timesfm,
            },
        )

    return {"available": True, **payload, "recorded": recorded}


@router.post("/api/future-simulation/actuals")
def api_future_simulation_actual(req: FutureSimulationActualRequest) -> dict:
    """将来財務予測へ実績値を戻し、後続レポートで誤差を測れるようにする。"""
    if req.sales is None and req.op_profit is None:
        raise HTTPException(status_code=422, detail="sales または op_profit の実績値が必要です")

    from api.prediction_snapshot import record_numeric_actual

    recorded = record_numeric_actual(
        case_id=req.case_id,
        observed_year=req.observed_year,
        sales=req.sales,
        op_profit=req.op_profit,
        observed_at=req.observed_at.isoformat(),
        source=req.source,
    )
    if recorded.get("status") == "error":
        raise HTTPException(status_code=500, detail=recorded.get("reason") or "実績記録に失敗しました")
    return recorded


@router.post("/api/forecast", response_model=ForecastResponse)
def api_forecast(req: ForecastRequest):
    from timesfm_engine import TIMESFM_AVAILABLE
    from datetime import date
    sales_hist = _annual_to_monthly(req.sales, req.industry)
    profit_hist = _annual_to_monthly(req.profit, req.industry)
    net_assets_hist = _annual_to_monthly(req.net_assets, req.industry)

    today = date.today()
    history_labels = _make_month_labels(today.year - 3, today.month, 36)
    forecast_labels = _make_month_labels(today.year, today.month, 12)

    return ForecastResponse(
        months_history=history_labels,
        sales_history=sales_hist,
        profit_history=profit_hist,
        net_assets_history=net_assets_hist,
        months_forecast=forecast_labels,
        sales_forecast=_run_forecast(sales_hist, 12),
        profit_forecast=_run_forecast(profit_hist, 12),
        net_assets_forecast=_run_forecast(net_assets_hist, 12),
        timesfm_available=TIMESFM_AVAILABLE,
    )
