#!/usr/bin/env python3
"""Build a read-only Memory Engineering report for Shion.

This report observes the full memory lifecycle:

- write path: candidate records generated by extraction jobs
- promotion path: preview rules that became active canonical rules
- read path: memory records actually recalled by chat surfaces
- maintenance path: stale/private/revised/deprecated records and contradictions

It does not delete, promote, or rewrite memory. The output is meant to make
"forgetting on purpose" reviewable before any human-approved cleanup.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_OUTPUT_JSON = REPO_ROOT / "reports" / "memory_engineering_latest.json"
DEFAULT_OUTPUT_MD = REPO_ROOT / "reports" / "memory_engineering_latest.md"

DEFAULT_CANONICAL_PREVIEW = REPO_ROOT / "data" / "canonical_judgment_rules_preview.json"
DEFAULT_CANONICAL_ACTIVE = REPO_ROOT / "data" / "canonical_judgment_rules.json"
DEFAULT_MEMORY_INDEX = REPO_ROOT / "data" / "shion_memory_index.json"
DEFAULT_MEMORY_USAGE = REPO_ROOT / "data" / "shion_memory_usage_log.jsonl"
DEFAULT_CONTRADICTIONS = REPO_ROOT / "reports" / "shion_memory_contradictions_latest.json"
DEFAULT_RETRIEVAL_GRAPH = REPO_ROOT / "data" / "obsidian_retrieval_graph.json"
DEFAULT_MEMORY_REVIEW_STATE = REPO_ROOT / "data" / "memory_review_inbox_state.json"

DEFAULT_JSONL_SOURCES = [
    ("judgment_materials_preview", REPO_ROOT / "data" / "judgment_materials_preview.jsonl"),
    ("autoresearch_candidates", REPO_ROOT / "data" / "autoresearch_judgment_asset_candidates.jsonl"),
    ("reflection_action_candidates", REPO_ROOT / "data" / "reflection_action_candidates.jsonl"),
    ("prediction_error_candidates", REPO_ROOT / "data" / "prediction_error_update_candidates.jsonl"),
    ("obsidian_memory_insight_candidates", REPO_ROOT / "data" / "obsidian_memory_insight_candidates.jsonl"),
]

WRITE_POLICY_FIELDS = ("importance", "confidence", "trust_level", "provenance")

TERMINAL_REVIEW_STATUSES = {
    "accepted",
    "adopted",
    "adopted_with_edit",
    "approved",
    "promoted",
    "rejected",
    "revised",
    "held",
    "dismissed",
    "archived",
    "deprecated",
}

MAINTENANCE_STATUSES = {"stale", "deprecated", "revised", "superseded"}


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return rows
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict):
            rows.append(row)
    return rows


def _records_from_index(payload: Any) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    records = payload.get("records")
    if isinstance(records, list):
        return [r for r in records if isinstance(r, dict)]
    items = payload.get("items")
    if isinstance(items, list):
        return [r for r in items if isinstance(r, dict)]
    return []


def _canonical_rules(payload: Any, *, preview: bool) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    key = "canonical_rules" if preview else "rules"
    rules = payload.get(key)
    if not isinstance(rules, list):
        rules = payload.get("rules")
    return [r for r in (rules or []) if isinstance(r, dict)]


def _parse_date(value: Any) -> date | None:
    text = str(value or "")
    if not text:
        return None
    try:
        return datetime.strptime(text[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


def _status(row: dict[str, Any]) -> str:
    for key in ("status", "human_decision_status", "review_status", "promotion_status", "decision"):
        value = str(row.get(key) or "").strip()
        if value:
            return value
    return "unknown"


def _source_item_id(row: dict[str, Any]) -> str:
    for key in ("id", "candidate_id", "canonical_key", "event_id"):
        value = str(row.get(key) or "").strip()
        if value:
            return value
    seed = json.dumps(row, ensure_ascii=False, sort_keys=True)
    return __import__("hashlib").sha256(seed.encode("utf-8")).hexdigest()[:16]


def _review_status_for(source_name: str, row: dict[str, Any], review_state: dict[str, Any]) -> str | None:
    reviews = review_state.get("reviews") if isinstance(review_state.get("reviews"), dict) else {}
    inbox_id = f"{source_name}__{_source_item_id(row)}"
    review = reviews.get(inbox_id)
    if isinstance(review, dict):
        status = str(review.get("status") or "").strip()
        return status or None
    return None


def _is_review_open(status: str) -> bool:
    return status not in TERMINAL_REVIEW_STATUSES


def _estimate_tokens(text: str) -> int:
    # Cheap, deterministic proxy. Japanese text often lands closer to 2 chars/token,
    # but using 4 keeps this as a conservative relative indicator.
    return max(1, len(text) // 4) if text else 0


def summarize_jsonl_source(name: str, path: Path, review_state: dict[str, Any] | None = None) -> dict[str, Any]:
    rows = _read_jsonl(path)
    review_state = review_state or {}
    statuses = Counter(_review_status_for(name, row, review_state) or _status(row) for row in rows)
    open_rows = sum(count for status, count in statuses.items() if _is_review_open(status))
    token_estimate = sum(
        _estimate_tokens(
            " ".join(
                str(row.get(key) or "")
                for key in ("title", "canonical_statement", "proposed_change", "body", "hypothesis")
            )
        )
        for row in rows
    )
    missing_policy_fields = Counter(
        field for row in rows for field in WRITE_POLICY_FIELDS if row.get(field) in (None, "", {})
    )
    rows_with_full_policy_metadata = sum(
        1 for row in rows if all(row.get(field) not in (None, "", {}) for field in WRITE_POLICY_FIELDS)
    )
    return {
        "name": name,
        "path": str(path.relative_to(REPO_ROOT)) if path.is_relative_to(REPO_ROOT) else str(path),
        "records": len(rows),
        "open_review_records": open_rows,
        "by_status": dict(sorted(statuses.items())),
        "estimated_tokens": token_estimate,
        "write_policy_metadata": {
            "required_fields": list(WRITE_POLICY_FIELDS),
            "complete_records": rows_with_full_policy_metadata,
            "missing_by_field": dict(sorted(missing_policy_fields.items())),
        },
    }


def summarize_usage(rows: list[dict[str, Any]], *, today: date, recent_days: int) -> dict[str, Any]:
    cutoff = today - timedelta(days=recent_days)
    recent_rows: list[dict[str, Any]] = []
    ref_counts: Counter[str] = Counter()
    route_counts: Counter[str] = Counter()
    for row in rows:
        ts = _parse_date(row.get("ts"))
        if ts is not None and ts >= cutoff:
            recent_rows.append(row)
        route = str(row.get("route") or "unknown")
        route_counts[route] += 1
        for ref in row.get("refs") or []:
            ref_counts[str(ref)] += 1
    recent_ref_ids = {
        str(ref)
        for row in recent_rows
        for ref in (row.get("refs") or [])
        if str(ref)
    }
    return {
        "events": len(rows),
        "recent_days": recent_days,
        "recent_events": len(recent_rows),
        "unique_refs": len(ref_counts),
        "recent_unique_refs": len(recent_ref_ids),
        "all_ref_ids": sorted(ref_counts),
        "by_route": dict(sorted(route_counts.items())),
        "top_refs": [{"id": rid, "uses": count} for rid, count in ref_counts.most_common(10)],
    }


def summarize_memory_records(records: list[dict[str, Any]], usage_summary: dict[str, Any]) -> dict[str, Any]:
    by_type = Counter(str(r.get("memory_type") or "unknown") for r in records)
    by_status = Counter(str(r.get("status") or "active") for r in records)
    by_layer = Counter(str(r.get("memory_layer") or "unknown") for r in records)
    used_ids = {str(ref) for ref in usage_summary.get("all_ref_ids", []) if str(ref)}

    maintenance_count = sum(by_status.get(status, 0) for status in MAINTENANCE_STATUSES)
    active_unused = [
        r
        for r in records
        if str(r.get("status") or "active") == "active"
        and str(r.get("memory_type") or "") != "value_memory"
        and str(r.get("id") or "") not in used_ids
    ]
    active_unused.sort(
        key=lambda r: (
            str(r.get("last_used_at") or ""),
            str(r.get("created_at") or ""),
            str(r.get("id") or ""),
        )
    )

    return {
        "total_records": len(records),
        "by_type": dict(sorted(by_type.items())),
        "by_status": dict(sorted(by_status.items())),
        "by_layer": dict(sorted(by_layer.items())),
        "maintenance_status_records": maintenance_count,
        "active_non_value_without_top_usage": len(active_unused),
        "forgetting_review_sample": [
            {
                "id": str(r.get("id") or ""),
                "memory_type": str(r.get("memory_type") or ""),
                "status": str(r.get("status") or "active"),
                "created_at": str(r.get("created_at") or ""),
                "last_used_at": str(r.get("last_used_at") or ""),
                "source_path": str(r.get("source_path") or ""),
                "content": str(r.get("content") or "")[:140],
            }
            for r in active_unused[:10]
        ],
    }


def summarize_retrieval_graph(payload: Any) -> dict[str, Any]:
    summary = payload.get("summary") if isinstance(payload, dict) else {}
    if not isinstance(summary, dict):
        return {}
    raw = int(summary.get("estimated_raw_tokens") or 0)
    indexed = int(summary.get("estimated_index_tokens") or 0)
    reduction = summary.get("estimated_token_reduction_ratio")
    return {
        "notes": int(summary.get("notes") or 0),
        "edges": int(summary.get("edges") or 0),
        "estimated_raw_tokens": raw,
        "estimated_index_tokens": indexed,
        "estimated_token_reduction_ratio": float(reduction or 0.0),
        "estimated_tokens_avoided": max(0, raw - indexed),
    }


def summarize_write_policy(sources: list[dict[str, Any]]) -> dict[str, Any]:
    total = sum(int(source.get("records") or 0) for source in sources)
    complete = sum(
        int((source.get("write_policy_metadata") or {}).get("complete_records") or 0)
        for source in sources
    )
    missing: Counter[str] = Counter()
    for source in sources:
        for field, count in ((source.get("write_policy_metadata") or {}).get("missing_by_field") or {}).items():
            missing[str(field)] += int(count or 0)
    return {
        "required_fields": list(WRITE_POLICY_FIELDS),
        "candidate_records": total,
        "records_with_full_metadata": complete,
        "completion_rate": round(complete / total, 3) if total else None,
        "missing_by_field": dict(sorted(missing.items())),
    }


def build_report(
    *,
    canonical_preview: Any,
    canonical_active: Any,
    memory_index: Any,
    memory_usage_rows: list[dict[str, Any]],
    jsonl_sources: list[tuple[str, Path]],
    review_state: dict[str, Any] | None = None,
    contradictions: Any,
    retrieval_graph: Any,
    target_date: str | None = None,
    recent_days: int = 30,
) -> dict[str, Any]:
    today = _parse_date(target_date) or date.today()

    preview_rules = _canonical_rules(canonical_preview, preview=True)
    active_rules = _canonical_rules(canonical_active, preview=False)
    preview_statuses = Counter(_status(rule) for rule in preview_rules)
    active_ids = {str(rule.get("id") or "") for rule in active_rules if rule.get("id")}
    accepted_preview_ids = {
        str(rule.get("id") or "")
        for rule in preview_rules
        if _status(rule) in {"accepted_preview", "accepted", "approved"}
    }
    promoted_from_latest_preview = len(active_ids & accepted_preview_ids)

    source_summaries = [summarize_jsonl_source(name, path, review_state or {}) for name, path in jsonl_sources]
    source_candidate_total = sum(item["records"] for item in source_summaries)
    open_review_total = sum(item["open_review_records"] for item in source_summaries)
    write_policy_summary = summarize_write_policy(source_summaries)

    usage_summary = summarize_usage(memory_usage_rows, today=today, recent_days=recent_days)
    memory_records = _records_from_index(memory_index)
    memory_summary = summarize_memory_records(memory_records, usage_summary)

    contradiction_candidates = []
    if isinstance(contradictions, dict) and isinstance(contradictions.get("candidates"), list):
        contradiction_candidates = contradictions["candidates"]

    write_path_records = source_candidate_total + len(preview_rules)
    active_rule_count = len(active_rules)
    write_amplification = (
        round(write_path_records / active_rule_count, 2) if active_rule_count else None
    )
    promotion_rate = (
        round(promoted_from_latest_preview / len(accepted_preview_ids), 3)
        if accepted_preview_ids
        else None
    )

    report = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "date": today.isoformat(),
        "schema_version": 1,
        "mode": "read_only_memory_engineering_observation",
        "guardrail": "no_memory_delete_no_promotion_no_prompt_or_scoring_change",
        "summary": {
            "write_path_records": write_path_records,
            "active_canonical_rules": active_rule_count,
            "write_amplification_per_active_rule": write_amplification,
            "latest_preview_rules": len(preview_rules),
            "latest_preview_accepted": len(accepted_preview_ids),
            "latest_preview_promoted_to_active": promoted_from_latest_preview,
            "latest_preview_promotion_rate": promotion_rate,
            "open_human_review_records": open_review_total,
            "memory_records": memory_summary["total_records"],
            "recent_memory_usage_events": usage_summary["recent_events"],
            "recent_unique_memory_refs": usage_summary["recent_unique_refs"],
            "maintenance_status_records": memory_summary["maintenance_status_records"],
            "contradiction_candidates": len(contradiction_candidates),
            "write_policy_metadata_completion_rate": write_policy_summary["completion_rate"],
        },
        "write_path": {
            "sources": source_summaries,
            "canonical_preview": {
                "records": len(preview_rules),
                "by_status": dict(sorted(preview_statuses.items())),
            },
            "write_policy": write_policy_summary,
        },
        "promotion_path": {
            "active_rule_ids": sorted(active_ids),
            "accepted_preview_ids": sorted(accepted_preview_ids),
            "promoted_from_latest_preview": promoted_from_latest_preview,
            "promotion_rate": promotion_rate,
        },
        "read_path": usage_summary,
        "maintenance_path": {
            **memory_summary,
            "contradiction_candidates": len(contradiction_candidates),
        },
        "hardware_pressure_proxy": summarize_retrieval_graph(retrieval_graph),
        "recommendations": build_recommendations(
            write_path_records=write_path_records,
            active_rule_count=active_rule_count,
            open_review_total=open_review_total,
            maintenance_records=memory_summary["maintenance_status_records"],
            contradiction_count=len(contradiction_candidates),
            recent_unique_refs=usage_summary["recent_unique_refs"],
            write_policy_completion_rate=write_policy_summary["completion_rate"],
        ),
    }
    return report


def build_recommendations(
    *,
    write_path_records: int,
    active_rule_count: int,
    open_review_total: int,
    maintenance_records: int,
    contradiction_count: int,
    recent_unique_refs: int,
    write_policy_completion_rate: float | None = None,
) -> list[dict[str, str]]:
    recommendations: list[dict[str, str]] = []
    if write_policy_completion_rate is not None and write_policy_completion_rate < 0.8:
        recommendations.append(
            {
                "area": "write_policy",
                "action": "memory_entry_metadata_gate",
                "reason": "候補記憶に importance/confidence/trust_level/provenance が不足している。昇格前に共通メタを補う。",
            }
        )
    if active_rule_count and write_path_records / active_rule_count >= 10:
        recommendations.append(
            {
                "area": "write_path",
                "action": "candidate_budget_review",
                "reason": "active判断基準1件あたりの候補量が多い。抽出条件・重複統合・候補上限を見直す。",
            }
        )
    if open_review_total >= 20:
        recommendations.append(
            {
                "area": "control",
                "action": "human_review_batch",
                "reason": "人間レビュー待ちが溜まっている。自動昇格せず、上位候補だけ短時間で採否する。",
            }
        )
    if contradiction_count:
        recommendations.append(
            {
                "area": "maintenance",
                "action": "contradiction_review",
                "reason": "矛盾候補がある。片方を消す前に適用条件・日付・出典を確認する。",
            }
        )
    if maintenance_records:
        recommendations.append(
            {
                "area": "forgetting",
                "action": "stale_or_revised_cleanup",
                "reason": "stale/revised/deprecated の記憶がある。削除ではなく、隔離・統合・改訂を確認する。",
            }
        )
    if recent_unique_refs == 0:
        recommendations.append(
            {
                "area": "read_path",
                "action": "recall_logging_check",
                "reason": "直近の記憶使用が観測されていない。記憶が使われていないのか、ログが切れているのか確認する。",
            }
        )
    return recommendations


def build_markdown(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# Memory Engineering Report",
        "",
        f"- Generated: {payload['generated_at']}",
        f"- Mode: `{payload['mode']}`",
        f"- Guardrail: `{payload['guardrail']}`",
        "",
        "## Summary",
        "",
        f"- Write path records: {summary['write_path_records']}",
        f"- Active canonical rules: {summary['active_canonical_rules']}",
        f"- Write amplification / active rule: {summary['write_amplification_per_active_rule']}",
        f"- Open human review records: {summary['open_human_review_records']}",
        f"- Memory records: {summary['memory_records']}",
        f"- Recent memory usage: {summary['recent_memory_usage_events']} events / {summary['recent_unique_memory_refs']} refs",
        f"- Maintenance status records: {summary['maintenance_status_records']}",
        f"- Contradiction candidates: {summary['contradiction_candidates']}",
        f"- Write policy metadata completion: {summary.get('write_policy_metadata_completion_rate')}",
        "",
        "## Stanford Lens: Write Cost",
        "",
    ]
    for source in payload["write_path"]["sources"]:
        lines.append(
            f"- `{source['name']}`: {source['records']} records, "
            f"{source['open_review_records']} open review, ~{source['estimated_tokens']} tokens"
        )
    write_policy = payload["write_path"].get("write_policy") or {}
    lines += [
        f"- `canonical_preview`: {payload['write_path']['canonical_preview']['records']} records",
        f"- Write policy required fields: `{write_policy.get('required_fields', [])}`",
        f"- Write policy missing fields: `{write_policy.get('missing_by_field', {})}`",
        "",
        "## Microsoft Lens: Utility Density",
        "",
        f"- Latest accepted preview: {summary['latest_preview_accepted']}",
        f"- Promoted to active rules: {summary['latest_preview_promoted_to_active']}",
        f"- Promotion rate: {summary['latest_preview_promotion_rate']}",
        "",
        "## Anthropic Lens: Control",
        "",
    ]
    maintenance = payload["maintenance_path"]
    lines.append(f"- Status counts: `{maintenance['by_status']}`")
    lines.append(f"- Type counts: `{maintenance['by_type']}`")
    if maintenance["forgetting_review_sample"]:
        lines.append("")
        lines.append("### Forgetting Review Sample")
        lines.append("")
        for item in maintenance["forgetting_review_sample"][:5]:
            lines.append(
                f"- `{item['id']}` {item['memory_type']} "
                f"last_used={item['last_used_at'] or 'none'} source={item['source_path']}: "
                f"{item['content']}"
            )
    graph = payload.get("hardware_pressure_proxy") or {}
    lines += [
        "",
        "## Nvidia Lens: Retrieval Pressure",
        "",
        f"- Notes: {graph.get('notes', 0)} / Edges: {graph.get('edges', 0)}",
        f"- Estimated raw tokens: {graph.get('estimated_raw_tokens', 0)}",
        f"- Estimated index tokens: {graph.get('estimated_index_tokens', 0)}",
        f"- Estimated token reduction: {graph.get('estimated_token_reduction_ratio', 0.0)}",
        "",
        "## Recommended Next Checks",
        "",
    ]
    if payload["recommendations"]:
        for item in payload["recommendations"]:
            lines.append(f"- `{item['action']}` ({item['area']}): {item['reason']}")
    else:
        lines.append("- No urgent memory-engineering action detected.")
    return "\n".join(lines) + "\n"


def write_outputs(payload: dict[str, Any], output_json: Path, output_md: Path) -> None:
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    output_md.write_text(build_markdown(payload), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Shion Memory Engineering report")
    parser.add_argument("--canonical-preview", type=Path, default=DEFAULT_CANONICAL_PREVIEW)
    parser.add_argument("--canonical-active", type=Path, default=DEFAULT_CANONICAL_ACTIVE)
    parser.add_argument("--memory-index", type=Path, default=DEFAULT_MEMORY_INDEX)
    parser.add_argument("--memory-usage", type=Path, default=DEFAULT_MEMORY_USAGE)
    parser.add_argument("--contradictions", type=Path, default=DEFAULT_CONTRADICTIONS)
    parser.add_argument("--retrieval-graph", type=Path, default=DEFAULT_RETRIEVAL_GRAPH)
    parser.add_argument("--memory-review-state", type=Path, default=DEFAULT_MEMORY_REVIEW_STATE)
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT_JSON)
    parser.add_argument("--output-md", type=Path, default=DEFAULT_OUTPUT_MD)
    parser.add_argument("--date", default=None)
    parser.add_argument("--recent-days", type=int, default=30)
    args = parser.parse_args()

    payload = build_report(
        canonical_preview=_read_json(args.canonical_preview),
        canonical_active=_read_json(args.canonical_active),
        memory_index=_read_json(args.memory_index),
        memory_usage_rows=_read_jsonl(args.memory_usage),
        jsonl_sources=DEFAULT_JSONL_SOURCES,
        review_state=_read_json(args.memory_review_state),
        contradictions=_read_json(args.contradictions),
        retrieval_graph=_read_json(args.retrieval_graph),
        target_date=args.date,
        recent_days=args.recent_days,
    )
    write_outputs(payload, args.output_json, args.output_md)
    print(
        "Memory Engineering report: "
        f"{payload['summary']['write_path_records']} write-path records, "
        f"{payload['summary']['active_canonical_rules']} active rules, "
        f"{payload['summary']['open_human_review_records']} open reviews -> {args.output_md}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
