#!/usr/bin/env python3
"""Build a read-only Memory Engineering report for Shion.

This report observes the full memory lifecycle:

- write path: candidate records generated by extraction jobs
- promotion path: preview rules that became active canonical rules
- read path: memory records actually recalled by chat surfaces
- maintenance path: stale/private/revised/deprecated records and contradictions

It does not delete, promote, or rewrite memory. The output is meant to make
"forgetting on purpose" reviewable before any human-approved cleanup.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_OUTPUT_JSON = REPO_ROOT / "reports" / "memory_engineering_latest.json"
DEFAULT_OUTPUT_MD = REPO_ROOT / "reports" / "memory_engineering_latest.md"

DEFAULT_CANONICAL_PREVIEW = REPO_ROOT / "data" / "canonical_judgment_rules_preview.json"
DEFAULT_CANONICAL_ACTIVE = REPO_ROOT / "data" / "canonical_judgment_rules.json"
DEFAULT_MEMORY_INDEX = REPO_ROOT / "data" / "shion_memory_index.json"
DEFAULT_MEMORY_USAGE = REPO_ROOT / "data" / "shion_memory_usage_log.jsonl"
DEFAULT_CONTRADICTIONS = REPO_ROOT / "reports" / "shion_memory_contradictions_latest.json"
DEFAULT_RETRIEVAL_GRAPH = REPO_ROOT / "data" / "obsidian_retrieval_graph.json"
DEFAULT_MEMORY_REVIEW_STATE = REPO_ROOT / "data" / "memory_review_inbox_state.json"
DEFAULT_EXPERIENCE_FLYWHEEL = REPO_ROOT / "reports" / "experience_flywheel_latest.json"
DEFAULT_CHECKLIST_CANDIDATES = REPO_ROOT / "reports" / "experience_replay_checklist_candidates_latest.json"
DEFAULT_ACCEPTED_CHECKLIST = REPO_ROOT / "data" / "experience_replay_accepted_checklist.json"
DEFAULT_FIELD_REVIEW = REPO_ROOT / "reports" / "judgment_asset_field_review_latest.json"

DEFAULT_JSONL_SOURCES = [
    ("judgment_materials_preview", REPO_ROOT / "data" / "judgment_materials_preview.jsonl"),
    ("autoresearch_candidates", REPO_ROOT / "data" / "autoresearch_judgment_asset_candidates.jsonl"),
    ("reflection_action_candidates", REPO_ROOT / "data" / "reflection_action_candidates.jsonl"),
    ("prediction_error_candidates", REPO_ROOT / "data" / "prediction_error_update_candidates.jsonl"),
    ("obsidian_memory_insight_candidates", REPO_ROOT / "data" / "obsidian_memory_insight_candidates.jsonl"),
]

WRITE_POLICY_FIELDS = ("importance", "confidence", "trust_level", "provenance")

TERMINAL_REVIEW_STATUSES = {
    "accepted",
    "adopted",
    "adopted_with_edit",
    "approved",
    "promoted",
    "rejected",
    "revised",
    "held",
    "dismissed",
    "archived",
    "deprecated",
}

MAINTENANCE_STATUSES = {"stale", "deprecated", "revised", "superseded"}


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return rows
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict):
            rows.append(row)
    return rows


def _records_from_index(payload: Any) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    records = payload.get("records")
    if isinstance(records, list):
        return [r for r in records if isinstance(r, dict)]
    items = payload.get("items")
    if isinstance(items, list):
        return [r for r in items if isinstance(r, dict)]
    return []


def _canonical_rules(payload: Any, *, preview: bool) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    key = "canonical_rules" if preview else "rules"
    rules = payload.get(key)
    if not isinstance(rules, list):
        rules = payload.get("rules")
    return [r for r in (rules or []) if isinstance(r, dict)]


def _parse_date(value: Any) -> date | None:
    text = str(value or "")
    if not text:
        return None
    try:
        return datetime.strptime(text[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


def _status(row: dict[str, Any]) -> str:
    for key in ("status", "human_decision_status", "review_status", "promotion_status", "decision"):
        value = str(row.get(key) or "").strip()
        if value:
            return value
    return "unknown"


def _source_item_id(row: dict[str, Any]) -> str:
    for key in ("id", "candidate_id", "canonical_key", "event_id"):
        value = str(row.get(key) or "").strip()
        if value:
            return value
    seed = json.dumps(row, ensure_ascii=False, sort_keys=True)
    return __import__("hashlib").sha256(seed.encode("utf-8")).hexdigest()[:16]


def _review_status_for(source_name: str, row: dict[str, Any], review_state: dict[str, Any]) -> str | None:
    reviews = review_state.get("reviews") if isinstance(review_state.get("reviews"), dict) else {}
    inbox_id = f"{source_name}__{_source_item_id(row)}"
    review = reviews.get(inbox_id)
    if isinstance(review, dict):
        status = str(review.get("status") or "").strip()
        return status or None
    return None


def _is_review_open(status: str) -> bool:
    return status not in TERMINAL_REVIEW_STATUSES


def _estimate_tokens(text: str) -> int:
    # Cheap, deterministic proxy. Japanese text often lands closer to 2 chars/token,
    # but using 4 keeps this as a conservative relative indicator.
    return max(1, len(text) // 4) if text else 0


def summarize_jsonl_source(name: str, path: Path, review_state: dict[str, Any] | None = None) -> dict[str, Any]:
    rows = _read_jsonl(path)
    review_state = review_state or {}
    statuses = Counter(_review_status_for(name, row, review_state) or _status(row) for row in rows)
    open_rows = sum(count for status, count in statuses.items() if _is_review_open(status))
    token_estimate = sum(
        _estimate_tokens(
            " ".join(
                str(row.get(key) or "")
                for key in ("title", "canonical_statement", "proposed_change", "body", "hypothesis")
            )
        )
        for row in rows
    )
    missing_policy_fields = Counter(
        field for row in rows for field in WRITE_POLICY_FIELDS if row.get(field) in (None, "", {})
    )
    rows_with_full_policy_metadata = sum(
        1 for row in rows if all(row.get(field) not in (None, "", {}) for field in WRITE_POLICY_FIELDS)
    )
    return {
        "name": name,
        "path": str(path.relative_to(REPO_ROOT)) if path.is_relative_to(REPO_ROOT) else str(path),
        "records": len(rows),
        "open_review_records": open_rows,
        "by_status": dict(sorted(statuses.items())),
        "estimated_tokens": token_estimate,
        "write_policy_metadata": {
            "required_fields": list(WRITE_POLICY_FIELDS),
            "complete_records": rows_with_full_policy_metadata,
            "missing_by_field": dict(sorted(missing_policy_fields.items())),
        },
    }


def summarize_usage(rows: list[dict[str, Any]], *, today: date, recent_days: int) -> dict[str, Any]:
    cutoff = today - timedelta(days=recent_days)
    recent_rows: list[dict[str, Any]] = []
    ref_counts: Counter[str] = Counter()
    route_counts: Counter[str] = Counter()
    for row in rows:
        ts = _parse_date(row.get("ts"))
        if ts is not None and ts >= cutoff:
            recent_rows.append(row)
        route = str(row.get("route") or "unknown")
        route_counts[route] += 1
        for ref in row.get("refs") or []:
            ref_counts[str(ref)] += 1
    recent_ref_ids = {
        str(ref)
        for row in recent_rows
        for ref in (row.get("refs") or [])
        if str(ref)
    }
    return {
        "events": len(rows),
        "recent_days": recent_days,
        "recent_events": len(recent_rows),
        "unique_refs": len(ref_counts),
        "recent_unique_refs": len(recent_ref_ids),
        "all_ref_ids": sorted(ref_counts),
        "by_route": dict(sorted(route_counts.items())),
        "top_refs": [{"id": rid, "uses": count} for rid, count in ref_counts.most_common(10)],
    }


def summarize_memory_records(records: list[dict[str, Any]], usage_summary: dict[str, Any]) -> dict[str, Any]:
    by_type = Counter(str(r.get("memory_type") or "unknown") for r in records)
    by_status = Counter(str(r.get("status") or "active") for r in records)
    by_layer = Counter(str(r.get("memory_layer") or "unknown") for r in records)
    used_ids = {str(ref) for ref in usage_summary.get("all_ref_ids", []) if str(ref)}

    maintenance_count = sum(by_status.get(status, 0) for status in MAINTENANCE_STATUSES)
    active_unused = [
        r
        for r in records
        if str(r.get("status") or "active") == "active"
        and str(r.get("memory_type") or "") != "value_memory"
        and str(r.get("id") or "") not in used_ids
    ]
    active_unused.sort(
        key=lambda r: (
            str(r.get("last_used_at") or ""),
            str(r.get("created_at") or ""),
            str(r.get("id") or ""),
        )
    )

    return {
        "total_records": len(records),
        "by_type": dict(sorted(by_type.items())),
        "by_status": dict(sorted(by_status.items())),
        "by_layer": dict(sorted(by_layer.items())),
        "maintenance_status_records": maintenance_count,
        "active_non_value_without_top_usage": len(active_unused),
        "forgetting_review_sample": [
            {
                "id": str(r.get("id") or ""),
                "memory_type": str(r.get("memory_type") or ""),
                "status": str(r.get("status") or "active"),
                "created_at": str(r.get("created_at") or ""),
                "last_used_at": str(r.get("last_used_at") or ""),
                "source_path": str(r.get("source_path") or ""),
                "content": str(r.get("content") or "")[:140],
            }
            for r in active_unused[:10]
        ],
    }


def summarize_retrieval_graph(payload: Any) -> dict[str, Any]:
    summary = payload.get("summary") if isinstance(payload, dict) else {}
    if not isinstance(summary, dict):
        return {}
    raw = int(summary.get("estimated_raw_tokens") or 0)
    indexed = int(summary.get("estimated_index_tokens") or 0)
    reduction = summary.get("estimated_token_reduction_ratio")
    return {
        "notes": int(summary.get("notes") or 0),
        "edges": int(summary.get("edges") or 0),
        "estimated_raw_tokens": raw,
        "estimated_index_tokens": indexed,
        "estimated_token_reduction_ratio": float(reduction or 0.0),
        "estimated_tokens_avoided": max(0, raw - indexed),
    }


def summarize_write_policy(sources: list[dict[str, Any]]) -> dict[str, Any]:
    total = sum(int(source.get("records") or 0) for source in sources)
    complete = sum(
        int((source.get("write_policy_metadata") or {}).get("complete_records") or 0)
        for source in sources
    )
    missing: Counter[str] = Counter()
    for source in sources:
        for field, count in ((source.get("write_policy_metadata") or {}).get("missing_by_field") or {}).items():
            missing[str(field)] += int(count or 0)
    return {
        "required_fields": list(WRITE_POLICY_FIELDS),
        "candidate_records": total,
        "records_with_full_metadata": complete,
        "completion_rate": round(complete / total, 3) if total else None,
        "missing_by_field": dict(sorted(missing.items())),
    }


def _summary_dict(payload: Any) -> dict[str, Any]:
    if isinstance(payload, dict) and isinstance(payload.get("summary"), dict):
        return payload["summary"]
    return {}


def _counter_from_mapping(payload: Any) -> dict[str, int]:
    if not isinstance(payload, dict):
        return {}
    result: dict[str, int] = {}
    for key, value in payload.items():
        try:
            result[str(key)] = int(value or 0)
        except (TypeError, ValueError):
            continue
    return result


def summarize_state_inventory(
    *,
    source_summaries: list[dict[str, Any]],
    preview_rules: list[dict[str, Any]],
    active_rules: list[dict[str, Any]],
    memory_summary: dict[str, Any],
    experience_flywheel: Any,
    checklist_candidates: Any,
    accepted_checklist: Any,
    field_review: Any,
) -> dict[str, Any]:
    """Build an inspectable active/candidate/quarantine/rejected inventory.

    This is deliberately descriptive, not authoritative. Each source keeps its
    own lifecycle rules; the inventory makes the current memory metabolism easy
    to review from one report.
    """
    source_statuses: Counter[str] = Counter()
    source_records = 0
    for source in source_summaries:
        source_records += int(source.get("records") or 0)
        for status, count in (source.get("by_status") or {}).items():
            source_statuses[str(status)] += int(count or 0)

    preview_statuses = Counter(_status(rule) for rule in preview_rules)
    flywheel_summary = _summary_dict(experience_flywheel)
    checklist_summary = _summary_dict(checklist_candidates)
    accepted_summary = _summary_dict(accepted_checklist)
    field_summary = _summary_dict(field_review)

    flywheel_by_gate = _counter_from_mapping(flywheel_summary.get("by_gate"))
    field_counts = {
        "grow": int(field_summary.get("grow") or 0),
        "review": int(field_summary.get("review") or 0),
        "sleeping": int(field_summary.get("sleeping") or 0),
        "hold": int(field_summary.get("hold") or 0),
    }
    checklist_review_counts = _counter_from_mapping(accepted_summary.get("review_counts"))

    candidate_count = (
        sum(count for status, count in source_statuses.items() if _is_review_open(status))
        + sum(
            count
            for status, count in preview_statuses.items()
            if status not in {"accepted_preview", "accepted", "approved", "promoted", "rejected"}
        )
        + int(flywheel_by_gate.get("promote_to_review") or 0)
        + int(flywheel_by_gate.get("replay_eval") or 0)
        + int(checklist_summary.get("candidate_count") or 0)
    )
    active_count = (
        len(active_rules)
        + int((memory_summary.get("by_status") or {}).get("active") or 0)
        + int(accepted_summary.get("active_count") or 0)
    )
    rejected_count = (
        sum(count for status, count in source_statuses.items() if status in {"rejected", "dismissed"})
        + int(checklist_review_counts.get("rejected") or 0)
    )
    quarantine_count = int(flywheel_by_gate.get("quarantine") or 0)
    maintenance_count = (
        int(memory_summary.get("maintenance_status_records") or 0)
        + field_counts["review"]
        + field_counts["sleeping"]
    )

    checklist_candidate_count = int(checklist_summary.get("candidate_count") or 0)
    checklist_reviewed = sum(checklist_review_counts.values())
    checklist_review_rate = (
        round(checklist_reviewed / checklist_candidate_count, 3)
        if checklist_candidate_count
        else None
    )
    field_feedback_coverage = (
        round((field_counts["grow"] + field_counts["review"]) / int(field_summary.get("active_rules") or 0), 3)
        if int(field_summary.get("active_rules") or 0)
        else None
    )

    return {
        "counts": {
            "active": active_count,
            "candidate_or_review": candidate_count,
            "quarantine": quarantine_count,
            "rejected_or_dismissed": rejected_count,
            "maintenance_or_forgetting_review": maintenance_count,
        },
        "sources": {
            "jsonl_candidate_records": source_records,
            "jsonl_by_status": dict(sorted(source_statuses.items())),
            "canonical_preview_by_status": dict(sorted(preview_statuses.items())),
            "experience_flywheel_by_gate": flywheel_by_gate,
            "field_review": field_counts,
            "checklist_candidates": {
                "candidate_count": checklist_candidate_count,
                "active_count": int(accepted_summary.get("active_count") or 0),
                "unreviewed_count": int(accepted_summary.get("unreviewed_count") or 0),
                "review_counts": checklist_review_counts,
                "review_rate": checklist_review_rate,
            },
        },
        "utility_kpis": {
            "checklist_review_rate": checklist_review_rate,
            "field_feedback_coverage": field_feedback_coverage,
            "candidate_to_active_pressure": (
                round(candidate_count / active_count, 3) if active_count else None
            ),
            "quarantine_rate_in_experience_flywheel": (
                round(quarantine_count / int(flywheel_summary.get("deduped_candidates") or 0), 3)
                if int(flywheel_summary.get("deduped_candidates") or 0)
                else None
            ),
        },
    }


def summarize_forgetting_policy(
    *,
    memory_summary: dict[str, Any],
    experience_flywheel: Any,
    field_review: Any,
) -> dict[str, Any]:
    flywheel_summary = _summary_dict(experience_flywheel)
    field_summary = _summary_dict(field_review)
    field_buckets = field_review.get("buckets") if isinstance(field_review, dict) else {}
    if not isinstance(field_buckets, dict):
        field_buckets = {}
    sleeping = field_buckets.get("sleeping") if isinstance(field_buckets.get("sleeping"), list) else []
    review = field_buckets.get("review") if isinstance(field_buckets.get("review"), list) else []
    by_gate = _counter_from_mapping(flywheel_summary.get("by_gate"))

    return {
        "policy": [
            {
                "class": "raw_logs",
                "rule": "Keep as evidence; distill into fact/skill/judgment candidates before recall.",
            },
            {
                "class": "candidate_memory",
                "rule": "Hold for human review; do not inject into prompts until accepted/revised.",
            },
            {
                "class": "active_but_sleeping",
                "rule": "Do not delete immediately; ask for real-case feedback or move to hold if it stays unused.",
            },
            {
                "class": "quarantine",
                "rule": "Keep out of memory and prompts; review only as a failure/poisoning/noise signal.",
            },
            {
                "class": "contradiction",
                "rule": "Surface with dates and applicability; never auto-merge contradictory memories.",
            },
        ],
        "current_pressure": {
            "active_non_value_without_top_usage": int(memory_summary.get("active_non_value_without_top_usage") or 0),
            "sleeping_active_rules": int(field_summary.get("sleeping") or 0),
            "review_active_rules": int(field_summary.get("review") or 0),
            "experience_quarantine": int(by_gate.get("quarantine") or 0),
        },
        "next_review_samples": {
            "unused_memory": memory_summary.get("forgetting_review_sample") or [],
            "sleeping_rules": [
                {
                    "rule_id": str(item.get("rule_id") or ""),
                    "concept": str(item.get("concept") or ""),
                    "reason": str(item.get("reason") or ""),
                    "statement": str(item.get("statement") or "")[:160],
                }
                for item in sleeping[:5]
                if isinstance(item, dict)
            ],
            "rules_needing_review": [
                {
                    "rule_id": str(item.get("rule_id") or ""),
                    "concept": str(item.get("concept") or ""),
                    "reason": str(item.get("reason") or ""),
                    "statement": str(item.get("statement") or "")[:160],
                }
                for item in review[:5]
                if isinstance(item, dict)
            ],
        },
    }


def _brief_text(value: Any, limit: int = 180) -> str:
    text = str(value or "").replace("\n", " ").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "…"


def _candidate_claim(row: dict[str, Any]) -> str:
    for key in ("claim", "canonical_statement", "proposed_change", "suggested_update", "body", "hypothesis"):
        value = _brief_text(row.get(key), 180)
        if value:
            return value
    return _brief_text(json.dumps(row, ensure_ascii=False, sort_keys=True), 180)


def _candidate_title(row: dict[str, Any]) -> str:
    for key in ("title", "research_title", "target_belief", "kind", "candidate_type", "material_type"):
        value = _brief_text(row.get(key), 80)
        if value:
            return value
    return _source_item_id(row)


def _open_candidate_samples(
    jsonl_sources: list[tuple[str, Path]],
    review_state: dict[str, Any],
    *,
    limit: int = 5,
) -> list[dict[str, Any]]:
    samples: list[dict[str, Any]] = []
    for source_name, path in jsonl_sources:
        for row in _read_jsonl(path):
            status = _review_status_for(source_name, row, review_state) or _status(row)
            if not _is_review_open(status):
                continue
            samples.append(
                {
                    "source": source_name,
                    "source_item_id": _source_item_id(row),
                    "status": status,
                    "title": _candidate_title(row),
                    "claim": _candidate_claim(row),
                    "topic": _brief_text(
                        row.get("research_topic")
                        or row.get("concept")
                        or row.get("target")
                        or row.get("domain"),
                        80,
                    ),
                    "date_hint": _brief_text(
                        row.get("research_date")
                        or row.get("date")
                        or row.get("target_date")
                        or row.get("created_at")
                        or row.get("generated_at"),
                        40,
                    ),
                    "review_command_hint": (
                        f"memory_review_inbox decision source={source_name} "
                        f"id={_source_item_id(row)}"
                    ),
                }
            )
    samples.sort(
        key=lambda item: (
            str(item.get("date_hint") or ""),
            str(item.get("source") or ""),
            str(item.get("source_item_id") or ""),
        ),
        reverse=True,
    )
    return samples[:limit]


def _quarantine_focus(experience_flywheel: Any, *, limit: int = 5) -> dict[str, Any]:
    items = []
    if isinstance(experience_flywheel, dict) and isinstance(experience_flywheel.get("quarantined_candidates"), list):
        items = [item for item in experience_flywheel["quarantined_candidates"] if isinstance(item, dict)]
    summary = _summary_dict(experience_flywheel)
    total_count = int(((summary.get("by_gate") or {}).get("quarantine") or 0) if isinstance(summary.get("by_gate"), dict) else 0)
    by_source = Counter(str(item.get("source") or "unknown") for item in items)
    by_reason = Counter(str((item.get("gate") or {}).get("reason") or "unknown") for item in items)
    samples: list[dict[str, Any]] = []
    for item in sorted(
        items,
        key=lambda row: (
            int((row.get("gate") or {}).get("priority") or 0),
            str(row.get("timestamp") or ""),
        ),
        reverse=True,
    )[:limit]:
        context = item.get("context") if isinstance(item.get("context"), dict) else {}
        decision = item.get("decision") if isinstance(item.get("decision"), dict) else {}
        gate = item.get("gate") if isinstance(item.get("gate"), dict) else {}
        samples.append(
            {
                "id": str(item.get("id") or ""),
                "source": str(item.get("source") or ""),
                "timestamp": str(item.get("timestamp") or ""),
                "reason": str(gate.get("reason") or ""),
                "recommended_action": str(gate.get("recommended_action") or ""),
                "question": _brief_text(context.get("question") or context.get("surface") or "", 140),
                "decision_preview": _brief_text(
                    decision.get("response_preview")
                    or decision.get("issue_text")
                    or decision.get("ringi_policy_text")
                    or decision,
                    180,
                ),
            }
        )
    return {
        "count": total_count or len(items),
        "sample_count": len(items),
        "sample_by_source": dict(sorted(by_source.items())),
        "sample_by_reason": dict(sorted(by_reason.items())),
        "review_hint": "Do not promote these. Use samples to tighten extraction gates or leave as evidence.",
        "samples": samples,
    }


def build_daily_review_focus(
    *,
    jsonl_sources: list[tuple[str, Path]],
    review_state: dict[str, Any],
    experience_flywheel: Any,
    forgetting_policy: dict[str, Any],
) -> dict[str, Any]:
    samples = forgetting_policy.get("next_review_samples") if isinstance(forgetting_policy, dict) else {}
    if not isinstance(samples, dict):
        samples = {}
    sleeping_rules = samples.get("sleeping_rules") if isinstance(samples.get("sleeping_rules"), list) else []
    unused_memory = samples.get("unused_memory") if isinstance(samples.get("unused_memory"), list) else []
    return {
        "mode": "read_only_daily_memory_engineering_focus",
        "actions": [
            {
                "id": "review_open_candidates",
                "label": "候補を少し採否する",
                "why": "候補圧を下げ、active memory へ進めるものと捨てるものを分ける。",
                "items": _open_candidate_samples(jsonl_sources, review_state, limit=5),
            },
            {
                "id": "inspect_quarantine_source",
                "label": "quarantine が多い抽出元を弱める",
                "why": "隔離候補は学習材料ではなく、抽出条件のノイズを示す。",
                "items": _quarantine_focus(experience_flywheel, limit=5),
            },
            {
                "id": "exercise_sleeping_active_rules",
                "label": "sleeping active rule を次案件で試すか保留する",
                "why": "active でも実利用フィードバックがなければ、判断資産として効いているか不明。",
                "items": sleeping_rules[:5],
            },
        ],
        "secondary_samples": {
            "unused_memory_for_forgetting_review": unused_memory[:5],
        },
    }


def build_report(
    *,
    canonical_preview: Any,
    canonical_active: Any,
    memory_index: Any,
    memory_usage_rows: list[dict[str, Any]],
    jsonl_sources: list[tuple[str, Path]],
    review_state: dict[str, Any] | None = None,
    contradictions: Any,
    retrieval_graph: Any,
    experience_flywheel: Any | None = None,
    checklist_candidates: Any | None = None,
    accepted_checklist: Any | None = None,
    field_review: Any | None = None,
    target_date: str | None = None,
    recent_days: int = 30,
) -> dict[str, Any]:
    today = _parse_date(target_date) or date.today()

    preview_rules = _canonical_rules(canonical_preview, preview=True)
    active_rules = _canonical_rules(canonical_active, preview=False)
    preview_statuses = Counter(_status(rule) for rule in preview_rules)
    active_ids = {str(rule.get("id") or "") for rule in active_rules if rule.get("id")}
    accepted_preview_ids = {
        str(rule.get("id") or "")
        for rule in preview_rules
        if _status(rule) in {"accepted_preview", "accepted", "approved"}
    }
    promoted_from_latest_preview = len(active_ids & accepted_preview_ids)

    source_summaries = [summarize_jsonl_source(name, path, review_state or {}) for name, path in jsonl_sources]
    source_candidate_total = sum(item["records"] for item in source_summaries)
    open_review_total = sum(item["open_review_records"] for item in source_summaries)
    write_policy_summary = summarize_write_policy(source_summaries)

    usage_summary = summarize_usage(memory_usage_rows, today=today, recent_days=recent_days)
    memory_records = _records_from_index(memory_index)
    memory_summary = summarize_memory_records(memory_records, usage_summary)
    state_inventory = summarize_state_inventory(
        source_summaries=source_summaries,
        preview_rules=preview_rules,
        active_rules=active_rules,
        memory_summary=memory_summary,
        experience_flywheel=experience_flywheel or {},
        checklist_candidates=checklist_candidates or {},
        accepted_checklist=accepted_checklist or {},
        field_review=field_review or {},
    )
    forgetting_policy = summarize_forgetting_policy(
        memory_summary=memory_summary,
        experience_flywheel=experience_flywheel or {},
        field_review=field_review or {},
    )
    daily_review_focus = build_daily_review_focus(
        jsonl_sources=jsonl_sources,
        review_state=review_state or {},
        experience_flywheel=experience_flywheel or {},
        forgetting_policy=forgetting_policy,
    )

    contradiction_candidates = []
    if isinstance(contradictions, dict) and isinstance(contradictions.get("candidates"), list):
        contradiction_candidates = contradictions["candidates"]

    write_path_records = source_candidate_total + len(preview_rules)
    active_rule_count = len(active_rules)
    write_amplification = (
        round(write_path_records / active_rule_count, 2) if active_rule_count else None
    )
    promotion_rate = (
        round(promoted_from_latest_preview / len(accepted_preview_ids), 3)
        if accepted_preview_ids
        else None
    )

    report = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "date": today.isoformat(),
        "schema_version": 1,
        "mode": "read_only_memory_engineering_observation",
        "guardrail": "no_memory_delete_no_promotion_no_prompt_or_scoring_change",
        "summary": {
            "write_path_records": write_path_records,
            "active_canonical_rules": active_rule_count,
            "write_amplification_per_active_rule": write_amplification,
            "latest_preview_rules": len(preview_rules),
            "latest_preview_accepted": len(accepted_preview_ids),
            "latest_preview_promoted_to_active": promoted_from_latest_preview,
            "latest_preview_promotion_rate": promotion_rate,
            "open_human_review_records": open_review_total,
            "memory_records": memory_summary["total_records"],
            "recent_memory_usage_events": usage_summary["recent_events"],
            "recent_unique_memory_refs": usage_summary["recent_unique_refs"],
            "maintenance_status_records": memory_summary["maintenance_status_records"],
            "contradiction_candidates": len(contradiction_candidates),
            "write_policy_metadata_completion_rate": write_policy_summary["completion_rate"],
            "candidate_to_active_pressure": state_inventory["utility_kpis"]["candidate_to_active_pressure"],
            "quarantine_records": state_inventory["counts"]["quarantine"],
            "sleeping_active_rules": forgetting_policy["current_pressure"]["sleeping_active_rules"],
        },
        "write_path": {
            "sources": source_summaries,
            "canonical_preview": {
                "records": len(preview_rules),
                "by_status": dict(sorted(preview_statuses.items())),
            },
            "write_policy": write_policy_summary,
        },
        "promotion_path": {
            "active_rule_ids": sorted(active_ids),
            "accepted_preview_ids": sorted(accepted_preview_ids),
            "promoted_from_latest_preview": promoted_from_latest_preview,
            "promotion_rate": promotion_rate,
        },
        "read_path": usage_summary,
        "maintenance_path": {
            **memory_summary,
            "contradiction_candidates": len(contradiction_candidates),
        },
        "state_inventory": state_inventory,
        "forgetting_policy": forgetting_policy,
        "daily_review_focus": daily_review_focus,
        "hardware_pressure_proxy": summarize_retrieval_graph(retrieval_graph),
        "recommendations": build_recommendations(
            write_path_records=write_path_records,
            active_rule_count=active_rule_count,
            open_review_total=open_review_total,
            maintenance_records=memory_summary["maintenance_status_records"],
            contradiction_count=len(contradiction_candidates),
            recent_unique_refs=usage_summary["recent_unique_refs"],
            write_policy_completion_rate=write_policy_summary["completion_rate"],
            candidate_to_active_pressure=state_inventory["utility_kpis"]["candidate_to_active_pressure"],
            quarantine_count=state_inventory["counts"]["quarantine"],
            sleeping_active_rules=forgetting_policy["current_pressure"]["sleeping_active_rules"],
        ),
    }
    return report


def build_recommendations(
    *,
    write_path_records: int,
    active_rule_count: int,
    open_review_total: int,
    maintenance_records: int,
    contradiction_count: int,
    recent_unique_refs: int,
    write_policy_completion_rate: float | None = None,
    candidate_to_active_pressure: float | None = None,
    quarantine_count: int = 0,
    sleeping_active_rules: int = 0,
) -> list[dict[str, str]]:
    recommendations: list[dict[str, str]] = []
    if write_policy_completion_rate is not None and write_policy_completion_rate < 0.8:
        recommendations.append(
            {
                "area": "write_policy",
                "action": "memory_entry_metadata_gate",
                "reason": "候補記憶に importance/confidence/trust_level/provenance が不足している。昇格前に共通メタを補う。",
            }
        )
    if active_rule_count and write_path_records / active_rule_count >= 10:
        recommendations.append(
            {
                "area": "write_path",
                "action": "candidate_budget_review",
                "reason": "active判断基準1件あたりの候補量が多い。抽出条件・重複統合・候補上限を見直す。",
            }
        )
    if open_review_total >= 20:
        recommendations.append(
            {
                "area": "control",
                "action": "human_review_batch",
                "reason": "人間レビュー待ちが溜まっている。自動昇格せず、上位候補だけ短時間で採否する。",
            }
        )
    if candidate_to_active_pressure is not None and candidate_to_active_pressure >= 0.25:
        recommendations.append(
            {
                "area": "utility_density",
                "action": "candidate_to_active_pressure_review",
                "reason": "active記憶に対して候補・評価待ちが重い。候補生成より採否・圧縮・却下の運用を優先する。",
            }
        )
    if quarantine_count:
        recommendations.append(
            {
                "area": "forgetting",
                "action": "quarantine_sample_review",
                "reason": "経験フライホイールに隔離候補がある。学習材料ではなく、抽出条件のノイズとして扱う。",
            }
        )
    if sleeping_active_rules:
        recommendations.append(
            {
                "area": "utility_density",
                "action": "sleeping_active_rule_feedback",
                "reason": "active判断資産に実利用フィードバック未記録のものがある。削除前に次案件で効いたか確認する。",
            }
        )
    if contradiction_count:
        recommendations.append(
            {
                "area": "maintenance",
                "action": "contradiction_review",
                "reason": "矛盾候補がある。片方を消す前に適用条件・日付・出典を確認する。",
            }
        )
    if maintenance_records:
        recommendations.append(
            {
                "area": "forgetting",
                "action": "stale_or_revised_cleanup",
                "reason": "stale/revised/deprecated の記憶がある。削除ではなく、隔離・統合・改訂を確認する。",
            }
        )
    if recent_unique_refs == 0:
        recommendations.append(
            {
                "area": "read_path",
                "action": "recall_logging_check",
                "reason": "直近の記憶使用が観測されていない。記憶が使われていないのか、ログが切れているのか確認する。",
            }
        )
    return recommendations


def build_markdown(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# Memory Engineering Report",
        "",
        f"- Generated: {payload['generated_at']}",
        f"- Mode: `{payload['mode']}`",
        f"- Guardrail: `{payload['guardrail']}`",
        "",
        "## Summary",
        "",
        f"- Write path records: {summary['write_path_records']}",
        f"- Active canonical rules: {summary['active_canonical_rules']}",
        f"- Write amplification / active rule: {summary['write_amplification_per_active_rule']}",
        f"- Open human review records: {summary['open_human_review_records']}",
        f"- Memory records: {summary['memory_records']}",
        f"- Recent memory usage: {summary['recent_memory_usage_events']} events / {summary['recent_unique_memory_refs']} refs",
        f"- Maintenance status records: {summary['maintenance_status_records']}",
        f"- Contradiction candidates: {summary['contradiction_candidates']}",
        f"- Write policy metadata completion: {summary.get('write_policy_metadata_completion_rate')}",
        f"- Candidate / active pressure: {summary.get('candidate_to_active_pressure')}",
        f"- Quarantine records: {summary.get('quarantine_records')}",
        f"- Sleeping active rules: {summary.get('sleeping_active_rules')}",
        "",
        "## Stanford Lens: Write Cost",
        "",
    ]
    for source in payload["write_path"]["sources"]:
        lines.append(
            f"- `{source['name']}`: {source['records']} records, "
            f"{source['open_review_records']} open review, ~{source['estimated_tokens']} tokens"
        )
    write_policy = payload["write_path"].get("write_policy") or {}
    lines += [
        f"- `canonical_preview`: {payload['write_path']['canonical_preview']['records']} records",
        f"- Write policy required fields: `{write_policy.get('required_fields', [])}`",
        f"- Write policy missing fields: `{write_policy.get('missing_by_field', {})}`",
        "",
        "## Microsoft Lens: Utility Density",
        "",
        f"- Latest accepted preview: {summary['latest_preview_accepted']}",
        f"- Promoted to active rules: {summary['latest_preview_promoted_to_active']}",
        f"- Promotion rate: {summary['latest_preview_promotion_rate']}",
        "",
        "## Anthropic Lens: Control",
        "",
    ]
    inventory = payload.get("state_inventory") or {}
    if inventory:
        lines += [
            f"- Lifecycle inventory: `{inventory.get('counts', {})}`",
            f"- Utility KPIs: `{inventory.get('utility_kpis', {})}`",
        ]
    maintenance = payload["maintenance_path"]
    lines.append(f"- Status counts: `{maintenance['by_status']}`")
    lines.append(f"- Type counts: `{maintenance['by_type']}`")
    if maintenance["forgetting_review_sample"]:
        lines.append("")
        lines.append("### Forgetting Review Sample")
        lines.append("")
        for item in maintenance["forgetting_review_sample"][:5]:
            lines.append(
                f"- `{item['id']}` {item['memory_type']} "
                f"last_used={item['last_used_at'] or 'none'} source={item['source_path']}: "
                f"{item['content']}"
            )
    forgetting = payload.get("forgetting_policy") or {}
    if forgetting:
        lines += [
            "",
            "## Forgetting Policy",
            "",
        ]
        for item in forgetting.get("policy") or []:
            lines.append(f"- `{item.get('class')}`: {item.get('rule')}")
        pressure = forgetting.get("current_pressure") or {}
        lines.append(f"- Current pressure: `{pressure}`")
        samples = (forgetting.get("next_review_samples") or {}).get("sleeping_rules") or []
        if samples:
            lines.append("")
            lines.append("### Sleeping Rule Sample")
            lines.append("")
            for item in samples[:5]:
                lines.append(
                    f"- `{item.get('rule_id')}` {item.get('concept')}: "
                    f"{item.get('statement')}"
                )
    focus = payload.get("daily_review_focus") or {}
    if focus:
        lines += [
            "",
            "## Daily Review Focus",
            "",
        ]
        for action in focus.get("actions") or []:
            lines.append(f"### {action.get('label')}")
            lines.append("")
            lines.append(f"- Why: {action.get('why')}")
            items = action.get("items")
            if isinstance(items, list):
                if items:
                    for item in items[:5]:
                        if action.get("id") == "review_open_candidates":
                            lines.append(
                                f"- `{item.get('source')}::{item.get('source_item_id')}` "
                                f"{item.get('title')}: {item.get('claim')}"
                            )
                        elif action.get("id") == "exercise_sleeping_active_rules":
                            lines.append(
                                f"- `{item.get('rule_id')}` {item.get('concept')}: "
                                f"{item.get('statement')}"
                            )
                        else:
                            lines.append(f"- `{item.get('id', '')}` {item}")
                else:
                    lines.append("- No items.")
            elif isinstance(items, dict):
                lines.append(f"- Count: {items.get('count', 0)}")
                lines.append(f"- Sample count: {items.get('sample_count', 0)}")
                lines.append(f"- Sample by source: `{items.get('sample_by_source', {})}`")
                lines.append(f"- Review hint: {items.get('review_hint', '')}")
                for item in items.get("samples") or []:
                    lines.append(
                        f"- `{item.get('id')}` {item.get('source')} "
                        f"{item.get('reason')}: {item.get('question') or item.get('decision_preview')}"
                    )
            lines.append("")
    graph = payload.get("hardware_pressure_proxy") or {}
    lines += [
        "",
        "## Nvidia Lens: Retrieval Pressure",
        "",
        f"- Notes: {graph.get('notes', 0)} / Edges: {graph.get('edges', 0)}",
        f"- Estimated raw tokens: {graph.get('estimated_raw_tokens', 0)}",
        f"- Estimated index tokens: {graph.get('estimated_index_tokens', 0)}",
        f"- Estimated token reduction: {graph.get('estimated_token_reduction_ratio', 0.0)}",
        "",
        "## Recommended Next Checks",
        "",
    ]
    if payload["recommendations"]:
        for item in payload["recommendations"]:
            lines.append(f"- `{item['action']}` ({item['area']}): {item['reason']}")
    else:
        lines.append("- No urgent memory-engineering action detected.")
    return "\n".join(lines) + "\n"


def write_outputs(payload: dict[str, Any], output_json: Path, output_md: Path) -> None:
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    output_md.write_text(build_markdown(payload), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Shion Memory Engineering report")
    parser.add_argument("--canonical-preview", type=Path, default=DEFAULT_CANONICAL_PREVIEW)
    parser.add_argument("--canonical-active", type=Path, default=DEFAULT_CANONICAL_ACTIVE)
    parser.add_argument("--memory-index", type=Path, default=DEFAULT_MEMORY_INDEX)
    parser.add_argument("--memory-usage", type=Path, default=DEFAULT_MEMORY_USAGE)
    parser.add_argument("--contradictions", type=Path, default=DEFAULT_CONTRADICTIONS)
    parser.add_argument("--retrieval-graph", type=Path, default=DEFAULT_RETRIEVAL_GRAPH)
    parser.add_argument("--memory-review-state", type=Path, default=DEFAULT_MEMORY_REVIEW_STATE)
    parser.add_argument("--experience-flywheel", type=Path, default=DEFAULT_EXPERIENCE_FLYWHEEL)
    parser.add_argument("--checklist-candidates", type=Path, default=DEFAULT_CHECKLIST_CANDIDATES)
    parser.add_argument("--accepted-checklist", type=Path, default=DEFAULT_ACCEPTED_CHECKLIST)
    parser.add_argument("--field-review", type=Path, default=DEFAULT_FIELD_REVIEW)
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT_JSON)
    parser.add_argument("--output-md", type=Path, default=DEFAULT_OUTPUT_MD)
    parser.add_argument("--date", default=None)
    parser.add_argument("--recent-days", type=int, default=30)
    args = parser.parse_args()

    payload = build_report(
        canonical_preview=_read_json(args.canonical_preview),
        canonical_active=_read_json(args.canonical_active),
        memory_index=_read_json(args.memory_index),
        memory_usage_rows=_read_jsonl(args.memory_usage),
        jsonl_sources=DEFAULT_JSONL_SOURCES,
        review_state=_read_json(args.memory_review_state),
        contradictions=_read_json(args.contradictions),
        retrieval_graph=_read_json(args.retrieval_graph),
        experience_flywheel=_read_json(args.experience_flywheel),
        checklist_candidates=_read_json(args.checklist_candidates),
        accepted_checklist=_read_json(args.accepted_checklist),
        field_review=_read_json(args.field_review),
        target_date=args.date,
        recent_days=args.recent_days,
    )
    write_outputs(payload, args.output_json, args.output_md)
    print(
        "Memory Engineering report: "
        f"{payload['summary']['write_path_records']} write-path records, "
        f"{payload['summary']['active_canonical_rules']} active rules, "
        f"{payload['summary']['open_human_review_records']} open reviews -> {args.output_md}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
